<!DOCTYPE html>
<html lang="en">

<head>

<meta charset="UTF-8">

<title>PayDZ Dashboard Report</title>


<style>

body{

    font-family: DejaVu Sans, sans-serif;

    color:#1e293b;

    font-size:12px;

}


.header{

    background:#059669;

    color:white;

    padding:20px;

    border-radius:10px;

}


.title{

    font-size:24px;

    font-weight:bold;

}



.card{

    margin-top:20px;

    padding:15px;

    border:1px solid #e2e8f0;

    border-radius:8px;

}



table{

    width:100%;

    border-collapse:collapse;

    margin-top:15px;

}



th{

    background:#f1f5f9;

    padding:10px;

    text-align:left;

}



td{

    padding:10px;

    border-bottom:1px solid #e2e8f0;

}



.footer{

    margin-top:30px;

    text-align:center;

    color:#64748b;

    font-size:11px;

}


</style>


</head>


<body>



<div class="header">


<div class="title">

PayDZ

</div>


<p>
Merchant Dashboard Report
</p>


</div>





<div class="card">


<h3>
Merchant Information
</h3>


<p>

<strong>Business:</strong>

{{ $merchant->business_name }}

</p>



<p>

<strong>Email:</strong>

{{ $merchant->business_email }}

</p>


<p>

<strong>Country:</strong>

{{ $merchant->country }}

</p>



</div>






<div class="card">


<h3>
Recent Payments
</h3>




<table>


<thead>

<tr>

<th>ID</th>

<th>Amount</th>

<th>Currency</th>

<th>Status</th>

<th>Date</th>


</tr>


</thead>




<tbody>


@foreach($payments as $payment)


<tr>


<td>

{{ $payment->id }}

</td>



<td>

{{ $payment->amount }}

</td>



<td>

{{ $payment->currency }}

</td>



<td>

{{ $payment->status }}

</td>



<td>

{{ $payment->created_at }}

</td>



</tr>


@endforeach



</tbody>


</table>



</div>






<div class="footer">


Generated by PayDZ Platform

</div>



</body>

</html>
